name: CI

on: push

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Build aseprite
      run: .github/scripts/build_aseprite.sh
    
    - name: Export sprites
      run: .github/scripts/export_sprites.sh
        
    - name: Push to "exported" branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: exported
        publish_dir: ./exported
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
